env:
  browser: true
  es2020: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 11
  sourceType: module
  project: [
    './tsconfig.json',
    './tsconfig.app.json',
    './tsconfig.base.json',
    './tsconfig.spec.json'
  ]
plugins:
  - '@typescript-eslint'
rules:
  # Possible Errors
  no-console:
  - warn

  # Best Practices
  dot-notation:
    - error
  no-magic-numbers:
    - warn
    - ignoreArrayIndexes: true
      ignore:
      - -1
      - 0
      - 1
  no-param-reassign:
    - error
  no-return-await: off
  no-unused-expressions:
    - error
  radix:
    - error

  # Strict Mode
  #

  # Variables
  no-unused-vars: off
  no-shadow:
    - error

  # Stylistic Issues
  camelcase: off
  comma-dangle:
    - error
    - never
  max-len:
    - warn
    - code: 140
      ignoreComments: true
      ignoreRegExpLiterals: true
      ignoreStrings: true
      ignoreTemplateLiterals: true
      ignoreTrailingComments: true
      ignoreUrls: true
  operator-linebreak:
    - error
    - before
  padded-blocks:
    - error
    - blocks: never
      classes: always
      switches: never
  eol-last:
    - error
  indent:
    - error
    - 2
  space-before-function-paren:
    - error
  quotes:
    - error
    - single

  # ECMAScript 6
  no-var:
    - error
  prefer-template:
    - error

  # Typescript
  "@typescript-eslint/adjacent-overload-signatures":
    - error
  "@typescript-eslint/array-type":
    - error
    - array: true
  "@typescript-eslint/ban-types":
    - error
    - types:
        any: null
  "@typescript-eslint/naming-convention":
    - error
    - selector: "variable"
      format: ["strictCamelCase", "snake_case", "UPPER_CASE"]
  "@typescript-eslint/explicit-function-return-type":
    - error
    - allowExpressions: true
      allowTypedFunctionExpressions: false
      allowHigherOrderFunctions: true
  "@typescript-eslint/member-delimiter-style":
    - error
  no-array-constructor: off
  "@typescript-eslint/no-array-constructor":
    - error
  "@typescript-eslint/no-empty-interface":
    - error
  "@typescript-eslint/no-explicit-any":
    - error
  "@typescript-eslint/no-misused-new":
    - error
  "@typescript-eslint/no-magic-numbers":
    - warn
    - ignoreEnums: true
      ignoreNumericLiteralTypes: true
      ignore:
      - -1
      - 0
      - 1
  "@typescript-eslint/no-namespace": off
  "@typescript-eslint/no-non-null-assertion":
    - error
  "@typescript-eslint/no-unused-vars":
    - error
  no-useless-constructor: off
  "@typescript-eslint/no-useless-constructor":
    - error
  "@typescript-eslint/no-use-before-define":
    - error
  "@typescript-eslint/prefer-includes":
    - error
  "@typescript-eslint/promise-function-async":
    - error
    - checkArrowFunctions: false
  "@typescript-eslint/semi":
    - error
  "@typescript-eslint/type-annotation-spacing":
    - error
  "@typescript-eslint/unified-signatures":
    - error